### ISSUE TITLE
FileNotFoundError when Dataset Preprocessing

### ISSUE THREAD

**Issue by Brianwongcw** [Large-Trajectory-Model/ATM#13]
Dear Authors:

When I preprocess the dataset using 
"python -m scripts.preprocess_libero --suite libero_spatial
python -m scripts.preprocess_libero --suite libero_object
python -m scripts.preprocess_libero --suite libero_goal
python -m scripts.preprocess_libero --suite libero_10
python -m scripts.preprocess_libero --suite libero_90"

The following error is encountered: 
```
(atm) nvidia@nvidia-System-Product-Name:~/Desktop/OpenSourceModel/ATM$ python -m scripts.preprocess_libero --suite libero_spatial
Traceback (most recent call last):
  File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/nvidia/Desktop/OpenSourceModel/ATM/scripts/preprocess_libero.py", line 285, in <module>
    main()
  File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/nvidia/Desktop/OpenSourceModel/ATM/scripts/preprocess_libero.py", line 268, in main
    cotracker = torch.hub.load(os.path.join(os.path.expanduser("~"), ".cache/torch/hub/facebookresearch_co-tracker_main/"), "cotracker2", source="local")
  File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/torch/hub.py", line 570, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/torch/hub.py", line 596, in _load_local
    hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
  File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/torch/hub.py", line 108, in _import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 975, in get_code
  File "<frozen importlib._bootstrap_external>", line 1032, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/home/nvidia/.cache/torch/hub/facebookresearch_co-tracker_main/hubconf.py'
```
Hope to get your reply. Thank you.

**Comment by yfpeng1234** [comment]
Hi Brian, I also encountered this problem, have you fixed it?

**Comment by Hunter-Wrynn** [comment]
> Dear Authors:
> 
> When I preprocess the dataset using "python -m scripts.preprocess_libero --suite libero_spatial python -m scripts.preprocess_libero --suite libero_object python -m scripts.preprocess_libero --suite libero_goal python -m scripts.preprocess_libero --suite libero_10 python -m scripts.preprocess_libero --suite libero_90"
> 
> The following error is encountered:
> 
> ```
> (atm) nvidia@nvidia-System-Product-Name:~/Desktop/OpenSourceModel/ATM$ python -m scripts.preprocess_libero --suite libero_spatial
> Traceback (most recent call last):
>   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/home/nvidia/Desktop/OpenSourceModel/ATM/scripts/preprocess_libero.py", line 285, in <module>
>     main()
>   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "/home/nvidia/Desktop/OpenSourceModel/ATM/scripts/preprocess_libero.py", line 268, in main
>     cotracker = torch.hub.load(os.path.join(os.path.expanduser("~"), ".cache/torch/hub/facebookresearch_co-tracker_main/"), "cotracker2", source="local")
>   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/torch/hub.py", line 570, in load
>     model = _load_local(repo_or_dir, model, *args, **kwargs)
>   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/torch/hub.py", line 596, in _load_local
>     hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
>   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/torch/hub.py", line 108, in _import_module
>     spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 839, in exec_module
>   File "<frozen importlib._bootstrap_external>", line 975, in get_code
>   File "<frozen importlib._bootstrap_external>", line 1032, in get_data
> FileNotFoundError: [Errno 2] No such file or directory: '/home/nvidia/.cache/torch/hub/facebookresearch_co-tracker_main/hubconf.py'
> ```
> 
> Hope to get your reply. Thank you.

git clone https://github.com/facebookresearch/co-tracker.git

**Comment by yfpeng1234** [comment]
Thanks a lot for your help! It works for me. BTW, the data pre-process is really time consuming.

**Comment by Brianwongcw** [comment]
> > Dear Authors:
> > When I preprocess the dataset using "python -m scripts.preprocess_libero --suite libero_spatial python -m scripts.preprocess_libero --suite libero_object python -m scripts.preprocess_libero --suite libero_goal python -m scripts.preprocess_libero --suite libero_10 python -m scripts.preprocess_libero --suite libero_90"
> > The following error is encountered:
> > ```
> > (atm) nvidia@nvidia-System-Product-Name:~/Desktop/OpenSourceModel/ATM$ python -m scripts.preprocess_libero --suite libero_spatial
> > Traceback (most recent call last):
> >   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/runpy.py", line 194, in _run_module_as_main
> >     return _run_code(code, main_globals, None,
> >   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/runpy.py", line 87, in _run_code
> >     exec(code, run_globals)
> >   File "/home/nvidia/Desktop/OpenSourceModel/ATM/scripts/preprocess_libero.py", line 285, in <module>
> >     main()
> >   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
> >     return self.main(*args, **kwargs)
> >   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/click/core.py", line 1078, in main
> >     rv = self.invoke(ctx)
> >   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
> >     return ctx.invoke(self.callback, **ctx.params)
> >   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/click/core.py", line 783, in invoke
> >     return __callback(*args, **kwargs)
> >   File "/home/nvidia/Desktop/OpenSourceModel/ATM/scripts/preprocess_libero.py", line 268, in main
> >     cotracker = torch.hub.load(os.path.join(os.path.expanduser("~"), ".cache/torch/hub/facebookresearch_co-tracker_main/"), "cotracker2", source="local")
> >   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/torch/hub.py", line 570, in load
> >     model = _load_local(repo_or_dir, model, *args, **kwargs)
> >   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/torch/hub.py", line 596, in _load_local
> >     hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
> >   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/torch/hub.py", line 108, in _import_module
> >     spec.loader.exec_module(module)
> >   File "<frozen importlib._bootstrap_external>", line 839, in exec_module
> >   File "<frozen importlib._bootstrap_external>", line 975, in get_code
> >   File "<frozen importlib._bootstrap_external>", line 1032, in get_data
> > FileNotFoundError: [Errno 2] No such file or directory: '/home/nvidia/.cache/torch/hub/facebookresearch_co-tracker_main/hubconf.py'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hope to get your reply. Thank you.
> 
> git clone https://github.com/facebookresearch/co-tracker.git

Already 'git clone https://github.com/facebookresearch/co-tracker.git' at the current folder 'ATM' and the parent folder, but it doesn't work. Do I need to perform the operation in a specific location?

**Comment by Hunter-Wrynn** [comment]
> > > Dear Authors:
> > > When I preprocess the dataset using "python -m scripts.preprocess_libero --suite libero_spatial python -m scripts.preprocess_libero --suite libero_object python -m scripts.preprocess_libero --suite libero_goal python -m scripts.preprocess_libero --suite libero_10 python -m scripts.preprocess_libero --suite libero_90"
> > > The following error is encountered:
> > > ```
> > > (atm) nvidia@nvidia-System-Product-Name:~/Desktop/OpenSourceModel/ATM$ python -m scripts.preprocess_libero --suite libero_spatial
> > > Traceback (most recent call last):
> > >   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/runpy.py", line 194, in _run_module_as_main
> > >     return _run_code(code, main_globals, None,
> > >   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/runpy.py", line 87, in _run_code
> > >     exec(code, run_globals)
> > >   File "/home/nvidia/Desktop/OpenSourceModel/ATM/scripts/preprocess_libero.py", line 285, in <module>
> > >     main()
> > >   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
> > >     return self.main(*args, **kwargs)
> > >   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/click/core.py", line 1078, in main
> > >     rv = self.invoke(ctx)
> > >   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
> > >     return ctx.invoke(self.callback, **ctx.params)
> > >   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/click/core.py", line 783, in invoke
> > >     return __callback(*args, **kwargs)
> > >   File "/home/nvidia/Desktop/OpenSourceModel/ATM/scripts/preprocess_libero.py", line 268, in main
> > >     cotracker = torch.hub.load(os.path.join(os.path.expanduser("~"), ".cache/torch/hub/facebookresearch_co-tracker_main/"), "cotracker2", source="local")
> > >   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/torch/hub.py", line 570, in load
> > >     model = _load_local(repo_or_dir, model, *args, **kwargs)
> > >   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/torch/hub.py", line 596, in _load_local
> > >     hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
> > >   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/torch/hub.py", line 108, in _import_module
> > >     spec.loader.exec_module(module)
> > >   File "<frozen importlib._bootstrap_external>", line 839, in exec_module
> > >   File "<frozen importlib._bootstrap_external>", line 975, in get_code
> > >   File "<frozen importlib._bootstrap_external>", line 1032, in get_data
> > > FileNotFoundError: [Errno 2] No such file or directory: '/home/nvidia/.cache/torch/hub/facebookresearch_co-tracker_main/hubconf.py'
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Hope to get your reply. Thank you.
> > 
> > 
> > git clone https://github.com/facebookresearch/co-tracker.git
> 
> Already 'git clone https://github.com/facebookresearch/co-tracker.git' at the current folder 'ATM' and the parent folder, but it doesn't work. Do I need to perform the operation in a specific location?

~/.cache/torch/hub/facebookresearch_co-tracker_main

**Comment by Brianwongcw** [comment]
> > > > Dear Authors:
> > > > When I preprocess the dataset using "python -m scripts.preprocess_libero --suite libero_spatial python -m scripts.preprocess_libero --suite libero_object python -m scripts.preprocess_libero --suite libero_goal python -m scripts.preprocess_libero --suite libero_10 python -m scripts.preprocess_libero --suite libero_90"
> > > > The following error is encountered:
> > > > ```
> > > > (atm) nvidia@nvidia-System-Product-Name:~/Desktop/OpenSourceModel/ATM$ python -m scripts.preprocess_libero --suite libero_spatial
> > > > Traceback (most recent call last):
> > > >   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/runpy.py", line 194, in _run_module_as_main
> > > >     return _run_code(code, main_globals, None,
> > > >   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/runpy.py", line 87, in _run_code
> > > >     exec(code, run_globals)
> > > >   File "/home/nvidia/Desktop/OpenSourceModel/ATM/scripts/preprocess_libero.py", line 285, in <module>
> > > >     main()
> > > >   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
> > > >     return self.main(*args, **kwargs)
> > > >   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/click/core.py", line 1078, in main
> > > >     rv = self.invoke(ctx)
> > > >   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
> > > >     return ctx.invoke(self.callback, **ctx.params)
> > > >   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/click/core.py", line 783, in invoke
> > > >     return __callback(*args, **kwargs)
> > > >   File "/home/nvidia/Desktop/OpenSourceModel/ATM/scripts/preprocess_libero.py", line 268, in main
> > > >     cotracker = torch.hub.load(os.path.join(os.path.expanduser("~"), ".cache/torch/hub/facebookresearch_co-tracker_main/"), "cotracker2", source="local")
> > > >   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/torch/hub.py", line 570, in load
> > > >     model = _load_local(repo_or_dir, model, *args, **kwargs)
> > > >   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/torch/hub.py", line 596, in _load_local
> > > >     hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
> > > >   File "/home/nvidia/miniconda3/envs/atm/lib/python3.8/site-packages/torch/hub.py", line 108, in _import_module
> > > >     spec.loader.exec_module(module)
> > > >   File "<frozen importlib._bootstrap_external>", line 839, in exec_module
> > > >   File "<frozen importlib._bootstrap_external>", line 975, in get_code
> > > >   File "<frozen importlib._bootstrap_external>", line 1032, in get_data
> > > > FileNotFoundError: [Errno 2] No such file or directory: '/home/nvidia/.cache/torch/hub/facebookresearch_co-tracker_main/hubconf.py'
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Hope to get your reply. Thank you.
> > > 
> > > 
> > > git clone https://github.com/facebookresearch/co-tracker.git
> > 
> > 
> > Already 'git clone https://github.com/facebookresearch/co-tracker.git' at the current folder 'ATM' and the parent folder, but it doesn't work. Do I need to perform the operation in a specific location?
> 
> ~/.cache/torch/hub/facebookresearch_co-tracker_main

The folder ~/.cache/torch/hub/facebookresearch_co-tracker_main does not exist, which is a bit strange. However, creating it manually resolved the issue. Thanks!
