### ISSUE TITLE
About stage 2： Track-guided Policy Training

### ISSUE THREAD

**Issue by Chen-lgc** [Large-Trajectory-Model/ATM#14]
When I run the commend 
`python -m scripts.train_libero_policy_atm --suite libero_spatial --tt results/track_transformer/libero_track_transformer_libero-spatial/`

The following error is encountered:
```
`(atm) (base) root@eb1ccb2cd4fa:~/home/ATM# python -m scripts.train_libero_policy_atm --suite libero_spatial -tt results/track_transformer/libero_track_transformer_libero-spatial/
[robosuite WARNING] No private macro file found! (macros.py:53)
[robosuite WARNING] It is recommended to use a private macro file (macros.py:54)
[robosuite WARNING] To setup, run: python /root/home/ATM/third_party/robosuite/robosuite/scripts/setup_macros.py (macros.py:55)
libEGL warning: DRI2: failed to create dri screen
libEGL warning: DRI2: failed to create dri screen
libEGL warning: DRI2: failed to create dri screen
libEGL warning: DRI2: failed to create dri screen
libEGL warning: DRI2: failed to create dri screen
libEGL warning: DRI2: failed to create dri screen
libEGL warning: DRI2: failed to create dri screen
libEGL warning: DRI2: failed to create dri screen
Seed set to 0
found 100 trajectories in the specified folders:

......

: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options`
```

How can I solve these problems? Hope to get your reply. Thank you!

**Comment by Holmes-GU** [comment]
I encounter the same issue, how can I fix it?

**Comment by Chen-lgc** [comment]
> I encounter the same issue, how can I fix it?

你在用Ubuntu20.04吗。可能是LLVM12的问题，我把系统中所有与llvm相关的包删除（除了llvmlite），安装llvm14，没有报上述错误了。

**Comment by yutchina** [comment]
> > 我遇到了同样的问题，我该如何解决？
> 
> 你在用Ubuntu20.04吗。可能是LLVM12的问题，我把系统中所有与llvm相关的包删除（除了llvmlite），安装llvm14，没有报上述错误了。

我还是遇到了类似的问题，我把llvm12删除后，手动安装了llvm14，但是出现了ImportError: libGL.so.1: cannot open shared object file: No such file or directory的问题，我安装这个lib后，llvm12奇迹般的自动安装了。我删除llvm12后，又报了ImportError: libGL.so.1: cannot open shared object file: No such file or directory的错误，你有什么好的办法吗？

**Comment by Chen-lgc** [comment]
> > > 我遇到了同样的问题，我该如何解决？
> > 
> > 
> > 你在用Ubuntu20.04吗。可能是LLVM12的问题，我把系统中所有与llvm相关的包删除（除了llvmlite），安装llvm14，没有报上述错误了。
> 
> 我还是遇到了类似的问题，我把llvm12删除后，手动安装了llvm14，但是出现了ImportError: libGL.so.1: cannot open shared object file: No such file or directory的问题，我安装这个lib后，llvm12奇迹般的自动安装了。我删除llvm12后，又报了ImportError: libGL.so.1: cannot open shared object file: No such file or directory的错误，你有什么好的办法吗？

可以加我qq交流一下吗，1872622678

**Comment by Chen-lgc** [comment]
The code related to "build_env" was commented out, allowing the program to run successfully, but the impact of this change is unclear.

**Comment by yutchina** [comment]
> > > > 我遇到了同样的问题，我该如何解决？
> > > 
> > > 
> > > 你在用Ubuntu20.04吗。可能是LLVM12的问题，我把系统中所有与llvm相关的包删除（除了llvmlite），安装llvm14，没有报上述错误了。
> > 
> > 
> > 我还是遇到了类似的问题，我把llvm12删除后，手动安装了llvm14，但是出现了ImportError: libGL.so.1: cannot open shared object file: No such file or directory的问题，我安装这个lib后，llvm12奇迹般的自动安装了。我删除llvm12后，又报了ImportError: libGL.so.1: cannot open shared object file: No such file or directory的错误，你有什么好的办法吗？
> 
> 可以加我qq交流一下吗，1872622678

你好 我通过新建一个全新的环境 然后根据代码缺少的包 一个个安装 最后解决了这个问题

**Comment by Chen-lgc** [comment]
> > > > > 我遇到了同样的问题，我该如何解决？
> > > > 
> > > > 
> > > > 你在用Ubuntu20.04吗。可能是LLVM12的问题，我把系统中所有与llvm相关的包删除（除了llvmlite），安装llvm14，没有报上述错误了。
> > > 
> > > 
> > > 我还是遇到了类似的问题，我把llvm12删除后，手动安装了llvm14，但是出现了ImportError: libGL.so.1: cannot open shared object file: No such file or directory的问题，我安装这个lib后，llvm12奇迹般的自动安装了。我删除llvm12后，又报了ImportError: libGL.so.1: cannot open shared object file: No such file or directory的错误，你有什么好的办法吗？
> > 
> > 
> > 可以加我qq交流一下吗，1872622678
> 
> 你好 我通过新建一个全新的环境 然后根据代码缺少的包 一个个安装 最后解决了这个问题

是不用environment.yml创建环境，一个个运行代码来安装包吗？可以列出新环境中安装的包吗？感谢

**Comment by yutchina** [comment]
> > > > > > 我遇到了同样的问题，我该如何解决？
> > > > > 
> > > > > 
> > > > > 你在用Ubuntu20.04吗。可能是LLVM12的问题，我把系统中所有与llvm相关的包删除（除了llvmlite），安装llvm14，没有报上述错误了。
> > > > 
> > > > 
> > > > 我还是遇到了类似的问题，我把llvm12删除后，手动安装了llvm14，但是出现了ImportError: libGL.so.1: cannot open shared object file: No such file or directory的问题，我安装这个lib后，llvm12奇迹般的自动安装了。我删除llvm12后，又报了ImportError: libGL.so.1: cannot open shared object file: No such file or directory的错误，你有什么好的办法吗？
> > > 
> > > 
> > > 可以加我qq交流一下吗，1872622678
> > 
> > 
> > 你好 我通过新建一个全新的环境 然后根据代码缺少的包 一个个安装 最后解决了这个问题
> 
> 是不用environment.yml创建环境，一个个运行代码来安装包吗？可以列出新环境中安装的包吗？感谢

是这样的 我用base跑的 差不多有600多个包 你需要吗？

**Comment by Chen-lgc** [comment]
> > > > > > > 我遇到了同样的问题，我该如何解决？
> > > > > > 
> > > > > > 
> > > > > > 你在用Ubuntu20.04吗。可能是LLVM12的问题，我把系统中所有与llvm相关的包删除（除了llvmlite），安装llvm14，没有报上述错误了。
> > > > > 
> > > > > 
> > > > > 我还是遇到了类似的问题，我把llvm12删除后，手动安装了llvm14，但是出现了ImportError: libGL.so.1: cannot open shared object file: No such file or directory的问题，我安装这个lib后，llvm12奇迹般的自动安装了。我删除llvm12后，又报了ImportError: libGL.so.1: cannot open shared object file: No such file or directory的错误，你有什么好的办法吗？
> > > > 
> > > > 
> > > > 可以加我qq交流一下吗，1872622678
> > > 
> > > 
> > > 你好 我通过新建一个全新的环境 然后根据代码缺少的包 一个个安装 最后解决了这个问题
> > 
> > 
> > 是不用environment.yml创建环境，一个个运行代码来安装包吗？可以列出新环境中安装的包吗？感谢
> 
> 是这样的 我用base跑的 差不多有600多个包 你需要吗？

要的，十分感谢

**Comment by MsterDC** [comment]
Hi, I recently encountered the same problem when reproducing it. 

I would like to know how this problem was finally solved? I hope someone can reply to me, thanks

**Comment by MsterDC** [comment]
> I encounter the same issue. How can I fix it?

Hi, have you solved this issue?
