### ISSUE TITLE
problem about training the track transformer

### ISSUE THREAD

**Issue by KaiTang98** [Large-Trajectory-Model/ATM#4]
Hello, thank you for presenting this interesting work. I am attempting to reproduce the training based on the **Libero** dataset. 

However, I've noticed that when training the track transformer, the **train_dataset_list** and **val1_dataset_list** obtained through:

train_dataset_list = glob(os.path.join(root_dir, f"{suite_name}//train/"))
val1_dataset_list = glob(os.path.join(root_dir, f"{suite_name}//val/"))

are **empty**. I'm wondering if the data preprocessing stage requires additional processing of the data obtained from preprocess_libero.py? Many thanks!
<img width="750" alt="image" src="https://github.com/Large-Trajectory-Model/ATM/assets/127410386/49508d9b-795b-45ee-977c-2012ca0c905f">
![image](https://github.com/Large-Trajectory-Model/ATM/assets/127410386/42b59b1d-226c-41bf-bf26-cc0d55657cb2)

**Comment by KaiTang98** [comment]
I checked the dataset inside **linero_goal** as an example. The dataset structure is shown as follows.
-- libero_goal
     -- open_the_middle_drawer....
          --images
          --videos
          --demo_0.hdf5
          --demo_1.hdf5
          --....hdf5
          --env_meta.json

**Comment by KaiTang98** [comment]
I realized that I just need to create these two folders by myself... Now I can train the model...

**Comment by caichuang0415** [comment]
> I realized that I just need to create these two folders by myself... Now I can train the model...😂😂

Thank you very much I have just come with this problem as well 😂😂

**Comment by yolo01826** [comment]
@KaiTang98 训练的结果怎么样，能够完成任务吗

**Comment by ahadjawaid** [comment]
I found the script you are suppose to run here is the command: 
```
python3 scripts/split_libero_dataset.py --folder data/atm_libero --train_ratio 0.9
```

**Comment by AlvinWen428** [comment]
Thank you very much for pointing this out. The "train" and "val" folders are generated by scripts/split_libero_dataset.py. Sorry for missing this important step in README. I have updated it.

**Comment by AlvinWen428** [comment]
Thank you very much for pointing this out. The "train" and "val" folders are generated by scripts/split_libero_dataset.py. Sorry for missing this important step in README. I have updated it.
