### ISSUE TITLE
The False Normalize Of Track Coordinates

### ISSUE THREAD

**Issue by caichuang0415** [Large-Trajectory-Model/ATM#6]
Thanks for your work.
I' ve been studing your codes recently and I found that the normalization of tracks in your scripts/preprocess_libero.py file maybe wrong. This is your code about it:
![z](https://github.com/Large-Trajectory-Model/ATM/assets/50684798/06138662-c448-4454-be12-6bdbb7d682a9)
as you can see, you divide the first value of track coord by H, and the second value of track coord by W.
Howerver, the tracks generated from cotracker 's first coord value is by the horizental direction to the image, and the second value is to the vertical. You can check that in [https://github.com/facebookresearch/co-tracker/blob/main/cotracker/utils/visualizer.py](url)

What's lucky is that the dataset you use has the same width and length, thus leaves no influence. But if is not, it may cause wrong training results

**Comment by AlvinWen428** [comment]
Thank you very much for pointing out this bug. I have fixed it.
